services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-scraping
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "5000:5000"
    volumes:
      - ./work:/work
      - ./credentials.json:/work/credentials.json:ro
      - ./.env:/work/.env:ro 
    depends_on:
      - selenium
    tty: true

  grok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http python:5000
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "4040:4040"
